function NeuroMaps
%% NeuroMaps – Main GUI for neural data analysis
% Description:
%   Launches the NeuroMaps GUI for visualizing and analysing multi-channel
%   neural recordings. Integrates spike, LFP, and network-level features,
%   supporting signal processing, QC, and analysis.
%
% Features:
%   - Raw & filtered signal plots (Waterfall, Signal Traces)
%   - Frequency Analysis (PSD, Spectrogram, CWT, FOOOF, Bandpower)
%   - Spike Features (Spikes, Clusters, ISI, Bursts, Amplitude, FWHM)
%   - Phase & Coupling Metrics (Phase plots, PAC)
%   - Network Dynamics (FR heatmaps, Rasters, STTC, Connectivity)
%   - Quality Control (Impedance, Noise, Flags)
%   - Probe Map integration for channel localisation
%
%
% Requirements:
%   MATLAB 2024b+, Signal Processing, Statistics, Wavelet, Econometrics,
%   Mapping Toolboxes. Python 3.11 with numpy, scipy, matplotlib, fooof.
%
% Author: Belquis Haider
% Date: 15-02-2025
% Updated: August 2025 - Belquis Haider
clc; close all force; clearvars;

try
    pyenv('ExecutionMode','OutOfProcess');
catch ME
    warning(ME.identifier, '%s', ME.message);
end

%% Create Figure Containing GUI 
% Width and Height Defined with respect to screen size, colours for backgrounds and text pre-defined

scrsz = get(0,'ScreenSize'); % Get Size of Computer Screen
figure_width = min(1280,scrsz(3)-40);
figure_height = min(720,scrsz(4)-120);

% Colour Definitions
set(0, 'DefaultFigureColor', [1 1 1]); % Example: white background
backgdcolor = [1, 1, 1]; % Background Colours RGB - default white
accentcolor = [0.1, 0.4, 0.6]; % Accent Colours RGB

h.figure = figure( ...
    'Units', 'pixels',...
    'NumberTitle', 'off', ...
    'Menubar', 'none', ...
    'Toolbar', 'auto', ...
    'Name', 'NeuroMaps (Molecular Neuroscience Group)', ...
    'Position', [20 scrsz(4)-figure_height-100 figure_width figure_height], ...
    'Color', backgdcolor); clf;

%% Create Menu for file operations and other functions
% File handling submenu
h.fileMenu = uimenu(h.figure, 'Label', 'Data Files');
uimenu(h.fileMenu, 'Label', 'Upload Raw Data', ...
       'Callback', @(src, event) openSystemSelectionDialog(h));

uimenu(h.fileMenu, 'Label', 'Upload Processed Data', ...
       'Callback', @(src, event) mult_file_analysed_expt_upload(h));

h.probe_config_menu = uimenu(h.figure, 'Label', 'Setup Probe');
uimenu(h.probe_config_menu, 'Label', 'Load Probe Map', ...
       'Callback', @(src,event) loadProbeMapCallback(h));
uimenu(h.probe_config_menu, 'Label', 'Define Probe Map', ...
       'Callback', @(src,event) probe_map_config([]));

%  Saving submenu
h.saveMenu = uimenu(h.figure, 'Label', 'Save');
uimenu(h.saveMenu, 'Label', 'Save Data', ...
       'Callback', @(src,event) save_output_callback(h));

uimenu(h.saveMenu, 'Label', 'Save GIF', ...
       'Callback', @(src,event) GIFy_callback(h));

%% Step Panel at the Top of the GUI
h.stepPanel = uipanel('Parent',h.figure,...
   'Units','normalized','Position',[0.05 0.91 0.90 0.06],'BackgroundColor',backgdcolor,'BorderType','none');
stepNames = {'1. Load Data','2. Filter Data', '3. Reference' , '4. Detect Spikes', '5. Validate Clusters' , 'Analyse LFP'};
nSteps = numel(stepNames);
pad = 0.01; btnW = (1-pad*(nSteps-1))/nSteps;btnH = 0.7;
h.stepBtns = gobjects(1,nSteps);
for k = 1:nSteps
    h.stepBtns(k) = uicontrol('Parent', h.stepPanel, 'Style','pushbutton', ...
        'Units','normalized', ...
        'Position', [ (k-1)*(btnW+pad), 0.05, btnW, btnH ], ...
        'String', stepNames{k}, ...
        'FontName','Arial','FontSize',8, ...
        'BackgroundColor', [1 1 1], ...
        'ForegroundColor', [0.25 0.25 0.25], ...
        'Callback', @(src,evt) stepperGo(k));
end
h.stepDone    = false(1,nSteps);
h.stepCurrent = 1;
% Initial highlight
stepperSet(h);

%% Tab Groups
% Left tab group: signals, frequency, spikes
h.tabgroup1 = uitabgroup('Parent',h.figure, 'Position', [0.05 0.11 0.45 0.80]);
% Right tab group: QC, probe, network, LFP
h.tabgroup2 = uitabgroup('Parent',h.figure, 'Position', [0.55 0.11 0.40 0.80]);
%% Main Tabs - Tab Group 1
h.summary_main_tab    = uitab(h.tabgroup1, 'Title', 'Data Log','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
%% Main Tabs - Tab Group 2
h.probe_map_tab       = uitab(h.tabgroup2, 'Title', 'Probe Map','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);

%% Nested Tabs - Probe Information
% Slider at Top of Screen For Scrolling through Channels
h.series_slider = uicontrol('Parent',h.probe_map_tab, ...
    'Style', 'slider',...
    'Units', 'normalized',...
    'Position', [0.02 0.96 0.30 0.03],...
    'Min', 1, ...
    'Max', 32,...
    'SliderStep', [0.25,0.25],...
    'BackgroundColor', backgdcolor,...
    'Visible', 'on',...
    'Value', 1,...
    'Callback', @(src,event) slider_callback([],[],h));

h.series_text = uicontrol(...
    'Parent',h.probe_map_tab, ...
    'Style', 'edit',...
    'Units', 'normalized',...
    'FontName', 'Arial',...
    'Fontsize', 11,...
    'HorizontalAlignment', 'Center',...
    'Position', [0.35 0.95 0.2 0.04],...
    'BackgroundColor', backgdcolor,...
    'Visible', 'on',...
    'String', '1',...
    'Callback', @(src,event) update_slider(h,src));

h.series_label = uicontrol('Parent', h.probe_map_tab, ...
    'Style','text','Units','normalized','Position', [0.55 0.95 0.2 0.04], ...
    'String','Port:Channel','BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);

% Right Panel
h.portsPanel = uipanel('Parent', h.probe_map_tab, ...
    'Title','Ports','Units','normalized','Position',[0.7 0.45 0.3 0.5],'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor);

h.probePlotPanel = uipanel('Parent', h.probe_map_tab, ...
    'Title','Probe Map','Units','normalized','Position',[0.02 0.05 0.68 0.9],'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor);

h.probe_map_axes = axes('Parent', h.probePlotPanel, ...
    'Units', 'normalized',...
    'Position', [0.01 0.1 0.99 0.85],...
    'FontName', 'Cambria',...
    'Fontsize', 8,'Visible','off');

% Load Maps
h.loadMapBtn = uicontrol('Parent', h.probe_map_tab, 'Style','pushbutton', ...
                         'String','Load Map', ...
                         'Units','normalized','Position',[0.02 0.01 0.15 0.03], ...
                         'Callback', @(src,evt) loadProbeMapCallback(h),'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor);

h.defineMapBtn = uicontrol('Parent', h.probe_map_tab, 'Style','pushbutton', ...
                           'String','Define Map', ...
                           'Units','normalized','Position',[0.18 0.01 0.15 0.03], ...
                           'Callback', @(src,evt) probe_map_config([]),'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor);


%% Data Logs
% Overview
h.summary_text = uicontrol('Style', 'edit', ...
    'Parent', h.summary_main_tab, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.05 0.9 0.9], ...
    'Max', 10, ... % allows multiple lines
    'HorizontalAlignment', 'left', ...
    'BackgroundColor', 'white', ...
    'FontName', 'Consolas', ...
    'FontSize', 11, ...
    'Enable', 'inactive');  % user can't edit, only view

% Setup Data Storage Tables
h.probe_map = uitable(...
    'Units', 'normalized',...
    'Position', [0 0 1 1 ],...
    'Visible' , 'off','Data',{ ...
        'sparseimg.tif'; ...
        'sparse_x_y_coords.mat'});
h.elecdesign = imread('sparseimg.tif');
set(h.probe_map_axes, 'Visible', 'on'); 
imshow(h.elecdesign, 'Parent', h.probe_map_axes); 
hold(h.probe_map_axes, 'on'); 
load('sparse_x_y_coords.mat', 'x_coords', 'y_coords', 'maps');
h.x_coords = x_coords;
h.y_coords = y_coords;
h.maps = maps;
h.marker = plot(h.probe_map_axes, NaN, NaN, 'bo', 'MarkerSize',4,'MarkerFaceColor','r'); % placeholder


h.bg = uibuttongroup('Parent',h.figure, ...
    'Units','normalized', ...
    'Position',[0.55 0.01 0.35 0.09],...
    'Title','Mapping Type', ...
    'BackgroundColor', backgdcolor, ...
    'Visible','on');
uicontrol('Style', 'radiobutton', ...
    'Parent', h.bg, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.25 0.3 0.35], ...
    'String', 'Topographic Map', ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor, ...
    'FontName', 'Cambria', 'FontSize', 11);

uicontrol('Style', 'radiobutton', ...
    'Parent', h.bg, ...
    'Units', 'normalized', ...
    'Position', [0.35 0.25 0.3 0.35], ...
    'String', 'Simple Map', ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor, ...
    'FontName', 'Cambria', 'FontSize', 11);

uicontrol('Style', 'radiobutton', ...
    'Parent', h.bg, ...
    'Units', 'normalized', ...
    'Position', [0.6 0.25 0.3 0.35], ...
    'String', 'Distribution', ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor, ...
    'FontName', 'Cambria', 'FontSize', 11);


% Exclusion Criteria Toggles
h.excl_imp_toggle = uicontrol('Style', 'checkbox', ...
    'Parent', h.figure, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.05 0.5 0.04], ... % adjust for spacing
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor, ...
    'FontName', 'Cambria', ...
    'FontSize', 11, ...
    'String', 'Exclude Bad Impedance Channels', ...
    'Value', 0,'Callback',@(src,event) exclude_signals(h)); 
h.excl_high_STD_toggle = uicontrol('Style', 'checkbox', ...
    'Parent', h.figure, ...
    'Units', 'normalized', ...
    'Position', [0.05 0.02 0.18 0.04], ... % adjust for spacing
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor, ...
    'FontName', 'Cambria', ...
    'FontSize', 11, ...
    'String', 'Exclude Noisy Channels', ...
    'Value', 0,'Callback',@(src,event) exclude_signals(h));

h.referenced_data_options = uitable(...
    'Units', 'normalized',...
    'Position', [0 0 1 1 ],...
    'Visible' , 'off');
guidata(h.figure,h)

function run_referencing_callback(~, ~, handles)
    h= guidata(h.figure);
    % Create a figure for user input
    fig = figure('Name', 'Referencing Options', 'Position', [100, 100, 300, 200], ...
        'MenuBar', 'none', 'ToolBar', 'none', 'NumberTitle', 'off');
    
    % Referencing type selection (radio buttons)
    uicontrol('Style', 'text', 'String', 'Select Referencing Type:', ...
        'BackgroundColor', backgdcolor,...
        'ForegroundColor',accentcolor,'Units', 'normalized', 'Position', [0.1, 0.7, 0.8, 0.1], 'Parent', fig);
    uicontrol('Style', 'radiobutton', 'String', 'Global', ...
        'Value',1,'Units', 'normalized', 'Position', [0.1, 0.6, 0.4, 0.1], ...
        'BackgroundColor', backgdcolor,...
        'ForegroundColor',accentcolor,'Parent', fig, 'Callback', {@referencing_type_callback, handles});
    set(handles.referenced_data_options, 'Data', {'global'});
    
    uicontrol('Style', 'radiobutton', 'String', 'Local (Coming Soon)', ...
        'Units', 'normalized', 'Position', [0.5, 0.6, 0.4, 0.1], ...
        'BackgroundColor', backgdcolor,...
        'ForegroundColor',accentcolor,'Parent', fig, 'Callback', {@referencing_type_callback, handles});
    
    % Operator selection (dropdown menu)
    uicontrol('Style', 'text', 'String', 'Select Operator:', ...
        'BackgroundColor', backgdcolor,...
        'ForegroundColor',accentcolor,'Units', 'normalized', 'Position', [0.1, 0.4, 0.8, 0.1], 'Parent', fig);
    
    operator_popup = uicontrol('Style', 'popupmenu', ...
        'String', {'','Median (Recommended)', 'Average'}, ...
        'BackgroundColor', backgdcolor,...
        'ForegroundColor',accentcolor,'Units', 'normalized', 'Position', [0.1, 0.3, 0.8, 0.1], ...
        'Parent', fig, 'Callback', {@operator_popup_callback, handles});
    
    % OK button to confirm selection
    uicontrol('Style', 'pushbutton', 'String', 'OK', ...
        'Units', 'normalized', 'Position', [0.4, 0.1, 0.2, 0.1], ...
        'Parent', fig, 'Callback', {@ok_button_callback, handles});
    
    % Wait for user input
    uiwait(fig);
end

function referencing_type_callback(src, ~, handles)
    % Callback function for referencing type selection (global/local)
    if strcmpi(src.String, 'Global')
        data = {'global'}; % Cell array with 'global' as string
    elseif contains(lower(src.String), 'local')
        data = {'local'};  % Cell array with 'local' as string
    end
    
    set(handles.referenced_data_options, 'Data', data);
end

function operator_popup_callback(src, ~, handles)
    % Callback function for operator selection (median/average)
    % Callback function for operator selection (median/average)
    selected_index = src.Value;
    options = src.String;
    
    % Determine the selected option
    selected_option = options{selected_index};
    
    % Set the Data property of referenced_data_options
    set(handles.referenced_data_options, 'UserData', {selected_option});
end

function ok_button_callback(~, ~, handles)
    % Callback function for OK button to close the figure and call external function
    delete(gcf); % Close the figure
    
    % Call external function with selected options
    run_referencing_pipeline(handles);
end


function updateSTDValue(src, handles,stdval)
    h = guidata(h.figure);
    % Callback function to update STD value
    new_val = get(src, 'Value');
    set(stdval, 'String', num2str(new_val, '%.1f'));
    update_thresholds(h);
    
end
function updateclusternumValue(src, handles)
    % Callback function to update STD value
    new_val = get(src, 'Value');
    set(handles.clusternums_value, 'String', num2str(new_val, '%.1f'));
    % Update your processing with the new STD value if necessary
end
function loadProbeMapCallback(h)
    h=guidata(h.figure);
    [imgFile, imgPath] = uigetfile({'*.tif;*.png;*.jpg', 'Image Files'}, ...
        'Select Probe Design Image');
    if isequal(imgFile,0)
        disp('Using default image.');
        imgFile='sparseimg.tif';

    end

    [matFile, matPath] = uigetfile('*.mat', 'Select Electrode Coordinate File');
    if isequal(matFile,0)
        disp('Using default coordinates.');
        matFile = 'sparse_x_y_coords.mat';
    end
    set(h.probe_map, 'Data', { ...
        fullfile(imgPath, imgFile); ...
        fullfile(matPath, matFile)});
    h.elecdesign = imread(imgFile);
    set(h.probe_map_axes, 'Visible', 'on'); 
    imshow(h.elecdesign, 'Parent', h.probe_map_axes); 
    hold(h.probe_map_axes, 'on'); 
    load(matFile, 'x_coords', 'y_coords', 'maps'); 
    h.x_coords = x_coords;
    h.y_coords = y_coords;
    h.maps = maps;
    h.marker = plot(h.probe_map_axes, NaN, NaN, 'bo', 'MarkerSize',4,'MarkerFaceColor','r'); 

    guidata(h.figure,h)
end


function openFilterSelectionDialog(h)
    h = guidata(h.figure);
    % Dialog size
    dialogHeight = 300;  
    d = dialog('Position', [400, 300, 450, dialogHeight], ...
               'Name', 'Configure Filters', ...
               'Color', backgdcolor);

    % Filter options (with parameter labels)
    filters = { ...
        'AC Line Noise', {'Notch Freq (Hz):', '50';'Bandwidth:', '2'}; ...
        'Low-pass Filter (LFP)', {'Cutoff (Hz):', '300'; 'Downsampled Frequency:', '1000'}; ...
        'Bandpass Filter (Spikes)', {'Low (Hz):', '300'; 'High (Hz):', '3000'; 'Order:', '3'} ...
    };

    numFilters = size(filters,1);
    cbHandles = gobjects(1,numFilters);
    paramHandles = cell(1,numFilters);

    % Layout each filter row
    for i = 1:numFilters
        yBase = 0.9 - (i-1)*0.25;

        % Checkbox
        cbHandles(i) = uicontrol('Parent', d, ...
            'Style', 'checkbox', ...
            'Units', 'normalized', ...
            'Position', [0.05, yBase-0.1, 0.4, 0.15], ...
            'String', {filters{i,1}}, ...
            'FontSize', 10, ...
            'BackgroundColor', backgdcolor, ...
            'ForegroundColor', accentcolor);
            % Parameters for this filter
        params = filters{i,2};
        paramEdits = gobjects(size(params,1),1);
        for j = 1:size(params,1)
            % Label
            uicontrol('Parent', d, ...
                'Style', 'text', ...
                'Units', 'normalized', ...
                'Position', [0.5, yBase - 0.07*(j-1), 0.2, 0.05], ...
                'String', params{j,1}, ...
                'BackgroundColor', backgdcolor, ...
                'HorizontalAlignment', 'right', ...
                'ForegroundColor', accentcolor);

            % Edit box
            paramEdits(j) = uicontrol('Parent', d, ...
                'Style', 'edit', ...
                'Units', 'normalized', ...
                'Position', [0.7, yBase - 0.07*(j-1), 0.2, 0.05], ...
                'String', params{j,2}, ...
                'BackgroundColor', 'w');
        end
        paramHandles{i} = paramEdits;
    end

    % Confirm button
    uicontrol('Parent', d, ...
        'Style', 'pushbutton', ...
        'Position', [120, 10, 100, 30], ...
        'String', 'Apply Filters', ...
        'Callback', @(src,event) confirmFilterSelection(h,d,cbHandles,paramHandles,filters));


function confirmFilterSelection(h,d,cbHandles,paramHandles,filters)
    selectedFilters = struct();

    for i = 1:length(cbHandles)
        if get(cbHandles(i), 'Value') == 1
            params = filters{i,2};
            paramEdits = paramHandles{i};
            vals = cell(size(params,1),1);
            for j = 1:size(params,1)
                vals{j} = str2double(get(paramEdits(j), 'String'));
            end
            % Build struct entry
            filterName = matlab.lang.makeValidName(filters{i,1});
            paramName = matlab.lang.makeValidName(params(:,1));
            selectedFilters.(filterName) = cell2struct(vals, paramName, 1);
        end
    end

    if isempty(fieldnames(selectedFilters))
        msgbox('Please select at least one filter.', 'Error', 'error');
    else
        h.selectedFilters = selectedFilters;
        delete(d);
        % Call your processing function with filters + params
        applyFilters(h);
    end

end
end

function stepperSet(h)
% Visually highlight the active step, dim the others
    idx = unique(h.stepCurrent);
    for i = 1:numel(h.stepBtns)
        if ismember(i,idx)
            set(h.stepBtns(i), 'BackgroundColor', hAccent(), 'ForegroundColor',[1 1 1], ...
                'FontWeight','bold');
        else
            set(h.stepBtns(i), 'BackgroundColor', [0.94 0.94 0.94], ...
                'ForegroundColor', [0.25 0.25 0.25], 'FontWeight','normal');
        end
    end
    guidata(h.figure,h);
end


function c = hAccent()  
    c = [0.1 0.4 0.6];
end
function stepperGo(idx)
    h=guidata(h.figure);
    switch idx
        case 1   % Load
                try openSystemSelectionDialog(h); catch, end
            % Focus a relevant tab
            try h.tabgroup1.SelectedTab = h.overview_main_tab; catch, end
        case 2   % Filter
            try openFilterSelectionDialog(h); catch, end
        case 3   % Reference
            try run_referencing_callback([],[],h); catch, end
        case 4   % Detect Spikes
            try run_spike_analysis(h); catch, end
            h=guidata(h.figure);
            try h.tabgroup1.SelectedTab = h.spike_detection_tab; catch, end
            try h.tabgroup2.SelectedTab = h.spikes_main_tab; catch, end
        case 5   %Validate Clusters
            try validate_clusters_callback(h); catch,end
        case 6   % LFP Analysis
            try fooof_callback(h); catch, end
    end
    h=guidata(h.figure);
    % Track state
    h.stepCurrent = [h.stepCurrent, idx];          % current step index
    % Initial highlight
    stepperSet(h);
    guidata(h.figure,h)
end

end
