function create_cumulative_tabs(h)
h= guidata(h.figure);
backgdcolor = [1, 1, 1]; % Background Colours RGB - default white
accentcolor = [0.1, 0.4, 0.6]; % Accent Colours RGB
if ~isfield(h,'cumulative_analysis_tab') || ~isvalid(h.cumulative_analysis_tab)
%  Cumulative Analysis Main Tab 
h.cumulative_analysis_tab = uitab(h.tabgroup1, ...
    'Title', 'Cumulative Analysis', ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor);

%  Tab Group inside Cumulative Analysis 
h.spike_analysis_tabs = uitabgroup('Parent', h.cumulative_analysis_tab, ...
    'Units', 'normalized', ...
    'Position', [0 0 1 1]);

%  Spikes Tab 
h.assess_spike_groups = uitab(h.spike_analysis_tabs, ...
    'Title', 'Spikes', ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor);
h.assess_spikes_button = uicontrol('Style', 'pushbutton', ...
    'Parent', h.assess_spike_groups, ...
    'String', 'Plot', ...
    'Units', 'normalized', ...
    'Position', [0.80, 0.0, 0.18, 0.05], ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor, ...
    'Callback', @(src, event) plot_all_spikes(h));

%  Clustering Tab 
h.cluster_spike_groups = uitab(h.spike_analysis_tabs, ...
    'Title', 'Clustering', ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor);
h.cluster_spikes_button = uicontrol('Style', 'pushbutton', ...
    'Parent', h.cluster_spike_groups, ...
    'String', 'Cluster', ...
    'Units', 'normalized', ...
    'Position', [0.80, 0.0, 0.18, 0.05], ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor, ...
    'Callback', @(src, event) cluster_all_spikes(h));
h.cluster_spikes_button = uicontrol('Style', 'pushbutton', ...
    'Parent', h.cluster_spike_groups, ...
    'String', 'Plot', ...
    'Units', 'normalized', ...
    'Position', [0.60, 0.0, 0.18, 0.05], ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor, ...
    'Callback', @(src, event) plot_all_clusters(h));
% Exclude button
h.exclude_button = uicontrol('Parent',h.cluster_spike_groups,'Style','pushbutton',...
    'String','Exclude Cluster','Units','normalized',...
    'Position',[0.8 0.045 0.18 0.045],...
    'Callback', @(src,evt) exclude_clusters(h),'Background',backgdcolor,'Foreground',accentcolor);
h.exp_pca_toggle = uicontrol('Style', 'checkbox', ...
    'Parent', h.cluster_spike_groups,'Units', 'normalized','Position', [0.05 0.005 0.3 0.06], ... 
    'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor, ...
    'FontName', 'Cambria', 'FontSize', 11, ...
    'String', 'Experiment PCA View', 'Value', 0); 
%  Statistics Tab 
h.group_stats = uitab(h.spike_analysis_tabs, ...
    'Title', 'Stats', ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor);
h.group_stats_button = uicontrol('Style', 'pushbutton', ...
    'Parent', h.group_stats, ...
    'String', 'Plot', ...
    'Units', 'normalized', ...
    'Position', [0.80, 0.0, 0.18, 0.05], ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor, ...
    'Callback', @(src, event) study_stats(h));

%  Evolution Tab 
h.group_evolution = uitab(h.spike_analysis_tabs, ...
    'Title', 'Evolution', ... 
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor);
h.group_evolution_button = uicontrol('Style', 'pushbutton', ...
    'Parent', h.group_evolution, ...
    'String', 'Plot', ...
    'Units', 'normalized', ...
    'Position', [0.80, 0.0, 0.18, 0.05], ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor, ...
    'Callback', @(src, event) study_evolution(h));
end
guidata(h.figure,h)
end