function create_spike_tabs(h)
h=guidata(h.figure);
backgdcolor = [1, 1, 1]; % Background Colours RGB - default white
accentcolor = [0.1, 0.4, 0.6]; % Accent Colours RGB
if ~isfield(h,'spike_detection_tab') || ~isvalid(h.spike_detection_tab)
h.spike_detection_tab = uitab(h.tabgroup1, 'Title', 'Spikes Overview','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.spikes_main_tab     = uitab(h.tabgroup2, 'Title', 'Firing Properties','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.spikes_features_tab    = uitab(h.tabgroup1, 'Title', 'Spike Features','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
%% Nested Spike Feature Tabs
h.spikedetectionTabs = uitabgroup('Parent', h.spike_detection_tab, 'Units', 'normalized', 'Position', [0 0 1 1]);
h.spike_summary_tab = uitab(h.spikedetectionTabs, 'Title', 'Spikes Summary','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.spike_summary_text = uicontrol('Style', 'edit', ...
    'Parent', h.spike_summary_tab,'Units', 'normalized','Position', [0.05 0.1 0.9 0.85], ...
    'Max', 10, 'HorizontalAlignment', 'left','BackgroundColor', 'white','FontName', 'Consolas', ...
    'FontSize', 11, 'Enable', 'inactive');  % user can't edit, only view
h.save_spike_summary_button = uicontrol('Style', 'pushbutton','Parent', h.spike_summary_tab,'String', 'Save Spike Summary', ...
'Units', 'normalized','Position', [0.70, 0.005, 0.25, 0.05],'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) save_summary_text(h));

h.parameter_definition_tab = uitab(h.spikedetectionTabs, 'Title', 'Parameters','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
% Panel for Network Connectivity Parameters
h.net_param_panel = uipanel('Parent', h.parameter_definition_tab, ...
    'Title', 'Network Connectivity Parameters', ...
    'Units', 'normalized', 'Position', [0.05 0.55 0.9 0.38], ...
    'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor, 'FontSize', 11);

uicontrol('Style', 'text', 'Parent', h.net_param_panel, ...
    'Units', 'normalized', 'Position', [0.05 0.8 0.6 0.1], ...
    'String', 'Acceptable spike delay window (ms):', ...
    'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor,'HorizontalAlignment','left');
h.dt_window = uicontrol('Style', 'edit', 'Parent', h.net_param_panel, ...
    'Units', 'normalized', 'Position', [0.7 0.8 0.25 0.1], ...
    'String', '20', 'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);

uicontrol('Style', 'text', 'Parent', h.net_param_panel, ...
    'Units', 'normalized', 'Position', [0.05 0.6 0.6 0.1], ...
    'String', 'Min. correlation value (0–1):', ...
    'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor, 'HorizontalAlignment','left');
h.min_corr = uicontrol('Style', 'edit', 'Parent', h.net_param_panel, ...
    'Units', 'normalized', 'Position', [0.7 0.6 0.25 0.1], ...
    'String', '0.6',  'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);

uicontrol('Style', 'text', 'Parent', h.net_param_panel, ...
    'Units', 'normalized', 'Position', [0.05 0.4 0.6 0.1], ...
    'String', 'Sender/Receiver threshold (0–1):', ...
    'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor,'HorizontalAlignment','left');
h.sr_thresh = uicontrol('Style', 'edit', 'Parent', h.net_param_panel, ...
    'Units', 'normalized', 'Position', [0.7 0.4 0.25 0.1], ...
    'String', '0.8', 'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);

uicontrol('Style', 'text', 'Parent', h.net_param_panel, ...
    'Units', 'normalized', 'Position', [0.05 0.2 0.6 0.1], ...
    'String', 'High/Medium corr thresholds (comma):', ...
    'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor, 'HorizontalAlignment','left');
h.hm_thresh = uicontrol('Style', 'edit', 'Parent', h.net_param_panel, ...
    'Units', 'normalized', 'Position', [0.7 0.2 0.25 0.1], ...
    'String', '0.7,0.3', 'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);

% Panel for Burst Detection Parameters
h.burst_param_panel = uipanel('Parent', h.parameter_definition_tab, ...
    'Title', 'Burst Detection Parameters', ...
    'Units', 'normalized', 'Position', [0.05 0.07 0.9 0.45], ...
    'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor, 'FontSize', 11);

labels = {'ISI Threshold (s):','Min Spikes per Burst:', ...
          'Min Burst Duration (s):','Min Spikes for Synchrony:','Binarisation Rate (Hz)'};
defaults = {'0.1','3','0.05','8','1000'};

for i = 1:numel(labels)
    uicontrol('Style','text','Parent',h.burst_param_panel, ...
        'Units','normalized','Position',[0.05 1-(i*0.18) 0.6 0.1], ...
        'String',labels{i},'BackgroundColor',backgdcolor,'ForegroundColor', accentcolor, ...
        'HorizontalAlignment','left');
    h.burst_param(i) = uicontrol('Style','edit','Parent',h.burst_param_panel, ...
        'Units','normalized','Position',[0.7 1-(i*0.18) 0.25 0.1], ...
        'String',defaults{i},'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
end


h.spikes_tab  = uitab(h.spikedetectionTabs, 'Title', 'Spikes','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.clusters_tab      = uitab(h.spikedetectionTabs, 'Title', 'Clusters','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.cluster_button = uicontrol('Style', 'pushbutton','Parent', h.clusters_tab,'String', 'Plot Clusters', ...
'Units', 'normalized','Position', [0.80, 0.0, 0.18, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) plot_cluster_callback(h));
h.cluster_plot_button = uicontrol('Style', 'pushbutton','Parent', h.clusters_tab,'String', 'Cluster Spikes', ...
'Units', 'normalized','Position', [0.60, 0.0, 0.18, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) clusters_callback(h));

h.cluster_exclusion_button = uicontrol('Style', 'pushbutton','Parent', h.clusters_tab,'String', 'Exclude Clusters', ...
'Units', 'normalized','Position', [0.40, 0.0, 0.18, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) exclude_clusters_callback(h));

h.clusternums_textbox = uicontrol( ...
    'Parent', h.clusters_tab, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.7 0.96 0.2 0.03], ... % Adjusted position within h.tab2
    'HorizontalAlignment', 'Left', ...
    'FontName', 'Calibri', ...
    'BackgroundColor', get(h.clusters_tab, 'BackgroundColor'), ...
    'Fontsize', 9, ...
    'String', 'Cluster Nums:');

h.clusternums_value = uicontrol(...
    'Parent', h.clusters_tab, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.95 0.96 0.05 0.03], ...
    'FontName', 'Calibri', ...
    'BackgroundColor', get(h.clusters_tab, 'BackgroundColor'), ...
    'Fontsize', 9, ...
    'String', '4'); % Default value
h.clusternums_slider = uicontrol(...
    'Parent', h.clusters_tab, ...
    'Style', 'slider', ...
    'Units', 'normalized', ...
    'Position', [0.85 0.96 0.1 0.03], ...
    'Min', 1, ...
    'Max', 20, ...
    'Value', 4, ...
    'SliderStep',[1/19 1/19], ...
    'BackgroundColor', get(h.clusters_tab, 'BackgroundColor'), ...
    'ForegroundColor',accentcolor,...
    'Callback', @(src, event) updateclusternumValue(src, h));
h.clusterListBox = uicontrol('Style', 'listbox', ...
                             'String','', ... % Example cluster IDs
                             'Parent',h.clusters_tab, ...
                             'Max', 10, ... % Maximum number of items that can be selected
                             'Min', 0, ... % Minimum number of items that can be selected
                             'Units','normalized','Position', [0.9, 0.05, 0.08, 0.1]); % Callback when selection change

h.clust_plot_toggle = uicontrol('Style', 'checkbox', ...
    'Parent', h.clusters_tab,'Units', 'normalized','Position', [0.05 0.005 0.3 0.06], ... 
    'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor, ...
    'FontName', 'Cambria', 'FontSize', 11, ...
    'String', 'Cluster View', 'Value', 0); 
 
%% Nested Tabs - Network Dynamics
h.spikeTabs = uitabgroup('Parent', h.spikes_main_tab, 'Units', 'normalized', 'Position', [0 0 1 1]);

h.fr_tab        = uitab(h.spikeTabs, 'Title', 'Firing Rates','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.firing_plot_button = uicontrol('Style', 'pushbutton','Parent', h.fr_tab,'String', 'Map', ...
'Units', 'normalized','Position', [0.80, 0.0, 0.18, 0.05],'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) plot_fr_callback(h));
h.firing_plot_settings_button = uicontrol('Style', 'pushbutton','Parent', h.fr_tab,'String', 'Plot Settings', ...
'Units', 'normalized','Position', [0.80, 0.06, 0.18, 0.05],'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) plot_setting_callback(h,1));

h.amp_tab        = uitab(h.spikeTabs, 'Title', 'Amplitudes','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.amp_plot_button = uicontrol('Style', 'pushbutton','Parent', h.amp_tab,'String', 'Map', ...
'Units', 'normalized','Position', [0.80, 0.0, 0.18, 0.05],'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) plot_amphm_callback(h));
h.amp_plot_settings_button = uicontrol('Style', 'pushbutton','Parent', h.amp_tab,'String', 'Plot Settings', ...
'Units', 'normalized','Position', [0.80, 0.06, 0.18, 0.05],'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) plot_setting_callback(h,2));

h.fr_toggle = uicontrol('Style', 'checkbox', ...
    'Parent', h.fr_tab,'Units', 'normalized','Position', [0.01 0.005 0.3 0.06], ... 
    'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor, ...
    'FontName', 'Cambria', 'FontSize', 11, ...
    'String', 'Overlay Waveforms', 'Value', 0,'Callback',@(src,event) plot_fr_callback(h));
h.fr_clust_toggle = uicontrol('Style', 'checkbox', ...
    'Parent', h.fr_tab,'Units', 'normalized','Position', [0.32 0.005 0.3 0.06], ... 
    'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor, ...
    'FontName', 'Cambria', 'FontSize', 11, ...
    'String', 'Overlay Clusters','Visible','off', 'Value', 0,'Callback',@(src,event) plot_fr_callback(h));

h.rast_tab      = uitab(h.spikeTabs, 'Title', 'Raster Plots','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.raster_plot_button = uicontrol('Style', 'pushbutton','Parent', h.rast_tab,'String', 'Raster', ...
'Units', 'normalized','Position', [0.80, 0.005, 0.18, 0.05],'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) plot_raster_callback(h));
h.rast_pop_plot_toggle = uicontrol('Style', 'checkbox', ...
    'Parent', h.rast_tab,'Units', 'normalized','Position', [0.01 0.005 0.5 0.06], ... 
    'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor, ...
    'FontName', 'Cambria', 'FontSize', 11, ...
    'String', 'Overlay Population Plot', 'Value', 0,'Callback',@(src,event) plot_raster_callback(h)); 
h.colorPopup = uicontrol('Parent', h.rast_tab, ...
                         'Style', 'popupmenu', ...
                         'String', {'Clusters','Amplitude','Black','Bursts'}, ...
                         'Units','normalized', ...
                         'Position', [0.5 0.005 0.2 0.05], ...  % adjust as needed
                         'Value', 3, ...  % default selection
                         'BackgroundColor', backgdcolor, ...
                         'ForegroundColor', accentcolor);

h.nws_tab       = uitab(h.spikeTabs, 'Title', 'Population Spiking','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.pop_spikes_plot_button = uicontrol('Style', 'pushbutton','Parent', h.nws_tab,'String', 'Population Activity Plot', ...
'Units', 'normalized','Position', [0.80, 0.0, 0.20, 0.05],'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) pop_spiking_plot(h)); 

h.synchrony_tab = uitab(h.spikeTabs, 'Title', 'STTC/Latency','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.sttc_plot_button = uicontrol('Style', 'pushbutton','Parent', h.synchrony_tab,'String', 'Plot', ...
'Units', 'normalized','Position', [0.80, 0.0, 0.18, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) compute_sttc_latency(h));
%%
h.FeatureTabs = uitabgroup('Parent', h.spikes_features_tab, 'Units', 'normalized', 'Position', [0 0 1 1]);
h.isi_tab           = uitab(h.FeatureTabs, 'Title', 'ISI','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.isi_plot_button = uicontrol('Style', 'pushbutton','Parent', h.isi_tab,'String', 'Plot ISI Distribution', ...
'Units', 'normalized','Position', [0.70, 0.0, 0.28, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) plot_isi_callback(h));
h.isi_plot_settings_button = uicontrol('Style', 'pushbutton','Parent', h.isi_tab,'String', 'Plot Settings', ...
'Units', 'normalized','Position', [0.53, 0.0, 0.18, 0.05],'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) histogram_settings_callback(h,1));

h.ibi_tab           = uitab(h.FeatureTabs, 'Title', 'Bursts','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.ibi_plot_button = uicontrol('Style', 'pushbutton','Parent', h.ibi_tab,'String', 'Plot IBI Distribution', ...
'Units', 'normalized','Position', [0.70, 0.0, 0.28, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) plot_ibi_callback(h));
h.ibi_plot_settings_button = uicontrol('Style', 'pushbutton','Parent', h.ibi_tab,'String', 'Plot Settings', ...
'Units', 'normalized','Position', [0.53, 0.0, 0.18, 0.05],'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) histogram_settings_callback(h,2));

h.amplitudes_tab    = uitab(h.FeatureTabs, 'Title', 'Amplitude','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.amplitudes_plot_button = uicontrol('Style', 'pushbutton','Parent', h.amplitudes_tab,'String', 'Plot Amplitudes', ...
'Units', 'normalized','Position', [0.70, 0.0, 0.28, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) plot_amplitudes_callback(h));
h.amplitudes_plot_settings_button = uicontrol('Style', 'pushbutton','Parent', h.amplitudes_tab,'String', 'Plot Settings', ...
'Units', 'normalized','Position', [0.53, 0.0, 0.18, 0.05],'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) histogram_settings_callback(h,3));

h.fwhm_tab          = uitab(h.FeatureTabs, 'Title', 'FWHM','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.fwhm_plot_button = uicontrol('Style', 'pushbutton','Parent', h.fwhm_tab,'String', 'Plot FWHM Distribution', ...
'Units', 'normalized','Position', [0.70, 0.0, 0.28, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) plot_fwhm_callback(h));
h.fwhm_plot_settings_button = uicontrol('Style', 'pushbutton','Parent', h.fwhm_tab,'String', 'Plot Settings', ...
'Units', 'normalized','Position', [0.53, 0.0, 0.18, 0.05],'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) histogram_settings_callback(h,4));

h.ph_tab = uitab(h.FeatureTabs, 'Title', 'Phase Plots','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.dvdt_plot_button = uicontrol('Style', 'pushbutton','Parent', h.ph_tab,'String', 'Plot', ...
'Units', 'normalized','Position', [0.70, 0.0, 0.28, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) plot_dvdt_phase(h));

h.feats_mode_toggle = uicontrol('Style', 'checkbox', ...
    'Parent', h.spikes_features_tab,'Units', 'normalized','Position', [0.05 0.005 0.2 0.06], ... 
    'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor, ...
    'FontName', 'Cambria', 'FontSize', 11, 'String', 'Global', 'Value', 0);
h.feats_clust_mode_toggl = uicontrol('Style', 'checkbox', ...
    'Parent', h.ph_tab,'Units', 'normalized','Position', [0.3 0.005 0.3 0.06], ... 
    'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor, ...
    'FontName', 'Cambria', 'FontSize', 11,'String', 'Cluster View', 'Value', 0); 
end
guidata(h.figure,h)

end