function create_lfp_foof_tabs(h)
h=guidata(h.figure);
backgdcolor = [1, 1, 1]; % Background Colours RGB - default white
accentcolor = [0.1, 0.4, 0.6]; % Accent Colours RGB
if ~isfield(h,'lfp_tab') || ~isvalid(h.lfp_tab)
h.lfp_tab = uitab(h.tabgroup1, 'Title', 'LFP Overview','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.FoooFTabs = uitabgroup('Parent', h.lfp_tab, 'Units', 'normalized', 'Position', [0 0 1 1]);
%  Create FOOOF Parameters Tab 
h.fooof_settings_tab = uitab(h.FoooFTabs, ...
    'Title', 'FOOOF Parameters', ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor);

%  Panel for FOOOF parameters 
h.fooof_panel = uipanel('Parent', h.fooof_settings_tab, ...
    'Title', 'FOOOF Fit Parameters', ...
    'Units', 'normalized', 'Position', [0.05 0.05 0.9 0.9], ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor, ...
    'FontSize', 11);

%  Peak width limits 
uicontrol('Style', 'text', 'Parent', h.fooof_panel, ...
    'Units', 'normalized', 'Position', [0.05 0.85 0.5 0.08], ...
    'String', 'Peak width limits (Hz, min,max):', ...
    'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor, ...
    'HorizontalAlignment','left');
h.peak_width = uicontrol('Style', 'edit', 'Parent', h.fooof_panel, ...
    'Units', 'normalized', 'Position', [0.6 0.85 0.35 0.08], ...
    'String', '1,8', 'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);

%  Max number of peaks 
uicontrol('Style', 'text', 'Parent', h.fooof_panel, ...
    'Units', 'normalized', 'Position', [0.05 0.7 0.5 0.08], ...
    'String', 'Max number of peaks:', ...
    'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor,'HorizontalAlignment','left');
h.max_n_peaks = uicontrol('Style', 'edit', 'Parent', h.fooof_panel, ...
    'Units', 'normalized', 'Position', [0.6 0.7 0.35 0.08], ...
    'String', 'Inf', 'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);

%  Min peak height 
uicontrol('Style', 'text', 'Parent', h.fooof_panel, ...
    'Units', 'normalized', 'Position', [0.05 0.55 0.5 0.08], ...
    'String', 'Min peak height:', ...
    'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor,'HorizontalAlignment','left');
h.min_peak_height = uicontrol('Style', 'edit', 'Parent', h.fooof_panel, ...
    'Units', 'normalized', 'Position', [0.6 0.55 0.35 0.08], ...
    'String', '0', 'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);

%  Peak threshold 
uicontrol('Style', 'text', 'Parent', h.fooof_panel, ...
    'Units', 'normalized', 'Position', [0.05 0.4 0.5 0.08], ...
    'String', 'Peak threshold:', ...
    'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor,'HorizontalAlignment','left');
h.peak_threshold = uicontrol('Style', 'edit', 'Parent', h.fooof_panel, ...
    'Units', 'normalized', 'Position', [0.6 0.4 0.35 0.08], ...
    'String', '1', 'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);

%  Aperiodic mode 
uicontrol('Style', 'text', 'Parent', h.fooof_panel, ...
    'Units', 'normalized', 'Position', [0.05 0.25 0.5 0.08], ...
    'String', 'Aperiodic mode:', ...
    'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor,'HorizontalAlignment','left');
h.aperiodic_mode = uicontrol('Style', 'popupmenu', 'Parent', h.fooof_panel, ...
    'Units', 'normalized', 'Position', [0.6 0.25 0.35 0.08], ...
    'String', {'fixed','knee'}, 'Value', 1, ...
    'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);

%  Verbose output 
h.verbose = uicontrol('Style', 'checkbox', 'Parent', h.fooof_panel, ...
    'Units', 'normalized', 'Position', [0.05 0.1 0.5 0.08], ...
    'String', 'Verbose output', 'Value', 1, ...
    'BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);

h.apply_fooof_button = uicontrol('Style', 'pushbutton', ...
    'Parent', h.fooof_panel, ...
    'Units', 'normalized', ...
    'Position', [0.35 0.02 0.3 0.05], ... % adjust as needed
    'String', 'Apply Parameters', ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor', accentcolor, ...
    'FontSize', 11, ...
    'Callback', @(src,event) apply_fooof_params(h));

h.foof_tab = uitab(h.FoooFTabs, 'Title', 'FOOOF Analysis', 'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.fooof_button = uicontrol('Style', 'pushbutton','Parent', h.foof_tab,'String', 'Plot','Units', 'normalized','Position', [0.80, 0.0, 0.20, 0.05],'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) PlotFooof_callback(h)); 
h.fooof_toggle = uicontrol('Style', 'checkbox','Parent', h.foof_tab,'Units', 'normalized', 'Position', [0.05 0 0.2 0.04], 'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor, ...
    'FontName', 'Cambria', 'FontSize', 11, 'String', 'Global', 'Value', 0,'Callback',@(src,event) PlotFooof_callback(h)); 

h.lfp_plots_tab = uitab(h.tabgroup2, 'Title', 'LFP Analysis','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
%% Nested Tabs - LFP Analysis
h.lfp_plot_Tabs = uitabgroup('Parent', h.lfp_plots_tab, 'Units', 'normalized', 'Position', [0 0 1 1]);
h.osc_tab       = uitab(h.lfp_plot_Tabs, 'Title', 'Oscillatory Plots','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.osc_plot_button = uicontrol('Style', 'pushbutton','Parent', h.osc_tab,'String', 'Plot Oscillatory Heatmap', ...
'Units', 'normalized','Position', [0.70, 0.0, 0.28, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) plot_osc_callback(h));

h.exps_tab      = uitab(h.lfp_plot_Tabs, 'Title', 'Exponents Plots','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.exp_plot_button = uicontrol('Style', 'pushbutton','Parent', h.exps_tab,'String', 'Plot Exponents Heatmap', ...
'Units', 'normalized','Position', [0.70, 0.0, 0.28, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) plot_exp_callback(h));

h.PAC_tab       = uitab(h.lfp_plot_Tabs, 'Title', 'PAC','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.PAC_plot_button = uicontrol('Style', 'pushbutton','Parent', h.PAC_tab,'String', 'Compute', ...
'Units', 'normalized','Position', [0.80, 0.0, 0.18, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) PAC_callback(h));

h.bandpower_tab = uitab(h.lfp_plot_Tabs, 'Title', 'Bandpower','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.bandpower_plot_button = uicontrol('Style', 'pushbutton','Parent', h.bandpower_tab,'String', 'Compute', ...
'Units', 'normalized','Position', [0.80, 0.0, 0.18, 0.05], ... % Adjust position as needed
'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) bandpower_callback(h));
h.time_resolved_bandpower = uicontrol('Style', 'checkbox','Parent', h.bandpower_tab,'Units', 'normalized', ...
    'Position', [0.05 0 0.6 0.04], 'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor, ...
    'FontName', 'Cambria', 'FontSize', 11, 'String', 'Time-resolved', 'Value', 0,'Callback',@(src,event) bandpower_callback(h)); 
end
guidata(h.figure,h)
end