function create_lfp_tabs(h)
backgdcolor = [1, 1, 1]; % Background Colours RGB - default white
accentcolor = [0.1, 0.4, 0.6]; % Accent Colours RGB
h= guidata(h.figure);

if ~isfield(h, 'cwt_tab') || ~isvalid(h.cwt_tab)
h.cwt_tab = uitab(h.SpectralTabs, 'Title', 'CWT',            'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.cwt_plot_button = uicontrol('Style', 'pushbutton','Parent', h.cwt_tab,'String', 'Plot CWT', ...
'Units', 'normalized','Position', [0.80, 0.0, 0.18, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) plot_cwt(h));

h.cwt_settings_button = uicontrol('Style', 'pushbutton','Parent', h.cwt_tab,'String', 'Plot Settings', ...
'Units', 'normalized','Position', [0.60, 0.0, 0.18, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) cwt_settings(h));

h.startLabel_cwt = uicontrol('Parent', h.cwt_tab, ...
    'Style','text','Units','normalized','Position', [0.0 0.01 0.2 0.03], ...
    'String','Start Time, End Time','BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);

h.timeBox_cwt = uicontrol('Parent', h.cwt_tab, ...
    'Style','edit','Units','normalized','Position',[0.21 0.01 0.15 0.04], ...
    'String','0,1','Callback', @(src,evt) plot_cwt(h,src));

h.cwt_plots_axes = axes('Parent', h.cwt_tab, ...
    'Units', 'normalized',...
    'Position', [0.1 0.1 0.85 0.85],...
    'FontName', 'Cambria',...
    'Fontsize', 8,'Visible','off');
end

guidata(h.figure,h);
end