function create_signal_tabs(h)
backgdcolor = [1, 1, 1]; % Background Colours RGB - default white
accentcolor = [0.1, 0.4, 0.6]; % Accent Colours RGB
if ~isfield(h,'overview_main_tab') || ~isvalid(h.overview_main_tab)
h.overview_main_tab   = uitab(h.tabgroup1, 'Title', 'Signal Traces','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.overviewTabs = uitabgroup('Parent', h.overview_main_tab,'Units', 'normalized','Position', [0 0 1 1]);
h.waterfall_tab = uitab(h.overviewTabs, 'Title', 'Waterfall Plots', 'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);

h.startLabel_waterfall = uicontrol('Parent', h.waterfall_tab, ...
    'Style', 'text','Units', 'normalized','Position', [0.2 0.01 0.17 0.03], ...
    'String', 'Start/End Time (s)','BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);
h.timeBox_waterfall = uicontrol('Parent', h.waterfall_tab, ...
    'Style','edit','Units','normalized','Position',[0.37 0.005 0.07 0.04], ...
    'String','0,60','Callback', @(src,evt) pop_graph_callback(h,src));
h.waterfall_settings_button = uicontrol('Parent', h.waterfall_tab, ...
'Style','pushbutton',...
'Units','normalized',...
'Position',[0.6 0.005 0.15 0.04],...  % adjust location
'String','Plot Settings',...
'BackgroundColor',backgdcolor,...
'ForegroundColor',accentcolor,...
'Callback', @(src,evt) waterfall_plot_settings(h));

h.export_waterfall_button = uicontrol('Parent', h.waterfall_tab, ...
'Style','pushbutton',...
'Units','normalized',...
'Position',[0.85 0.005 0.09 0.04],...  % adjust location
'String','Export',...
'BackgroundColor',backgdcolor,...
'ForegroundColor',accentcolor,...
'Callback', @(src,evt) export_full_waterfall_page(h));
h.plot_waterfall_button = uicontrol('Parent', h.waterfall_tab, ...
'Style','pushbutton',...
'Units','normalized',...
'Position',[0.75 0.005 0.09 0.04],...  % adjust location
'String','Plot',...
'BackgroundColor',backgdcolor,...
'ForegroundColor',accentcolor,...
'Callback', @(src,evt) pop_graph_callback(h));


% Channel Traces
h.traces_tab    = uitab(h.overviewTabs, 'Title', 'Signal Traces',   'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.traces_tab_button = uicontrol('Style', 'pushbutton','Parent', h.traces_tab,'String', 'Plot', ...
'Units', 'normalized','Position', [0.80, 0.0, 0.18, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, 'Callback', @(src, event) update_traces_tab(h));
h.traces_plot_settings = uicontrol('Style', 'pushbutton','Parent', h.traces_tab,'String', 'Plot Settings', ...
'Units', 'normalized','Position', [0.60, 0.0, 0.18, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, 'Callback', @(src, event) traces_settings(h));
% Add std_textbox within the tab2 panel (h.tab2)
h.std_textbox = uicontrol( ...
    'Parent', h.figure, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.23 0.05 0.15 0.04], ...
    'HorizontalAlignment', 'Left', ...
    'FontName', 'Calibri', ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor',accentcolor,'Visible', 'off','String', 'Minimum Spike Threshold Multiplier');
h.std_value = uicontrol(...
'Parent', h.figure, ...
'Style', 'edit', ...
'Units', 'normalized', ...
'Position', [0.37 0.07 0.04 0.02], ...
'String', '4.5','Visible', 'off', ...
'Callback', @(src,~) updateSTDFromEdit(src,h));
h.stdmax_textbox = uicontrol( ...
    'Parent', h.figure, ...
    'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.23 0.01 0.15 0.04], ...
    'HorizontalAlignment', 'Left', ...
    'FontName', 'Calibri', ...
    'BackgroundColor', backgdcolor, ...
    'ForegroundColor',accentcolor,'Visible', 'off','String', 'Outlier Detection Multiplier');
h.stdmax_value = uicontrol(...
'Parent', h.figure, ...
'Style', 'edit', ...
'Units', 'normalized', ...
'Position', [0.37 0.03 0.04 0.02], ...
'String', '10','Visible', 'off', ...
'Callback', @(src,~) updateSTDFromEdit(src,h));
h.std_button = uicontrol('Style', 'pushbutton','Parent', h.figure,'String', 'Update STD Limits', ...
'Units', 'normalized','Position', [0.42, 0.04, 0.08, 0.04], ... 
'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor,'Visible', 'off', ...
'Callback', @(src, event) update_thresholds(h));
end
if ~isfield(h,'freq_analysis_tab') || ~isvalid(h.freq_analysis_tab)
h.freq_analysis_tab   = uitab(h.tabgroup1, 'Title', 'Frequency Analysis','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
%% Nested Tabs - Frequency Analysis
h.SpectralTabs = uitabgroup('Parent', h.freq_analysis_tab, 'Units', 'normalized', 'Position', [0 0 1 1]);
h.pspec_tab    = uitab(h.SpectralTabs, 'Title', 'Power Spectrum',  'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.ps_plot_button = uicontrol('Style', 'pushbutton','Parent', h.pspec_tab,'String', 'Plot', ...
'Units', 'normalized','Position', [0.80, 0.0, 0.18, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) update_power_spectrum_tab(h));
h.pspec_toggle = uicontrol('Style', 'checkbox','Parent', h.pspec_tab,'Units', 'normalized', ...
    'Position', [0.05 0 0.2 0.05], 'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor, ...
    'String', 'Global', 'Value', 0,'Callback',@(src,event) update_power_spectrum_tab(h)); 

h.pspec_settings = uicontrol('Style','pushbutton','Parent', h.pspec_tab,'Units', 'normalized', ...
    'Position', [0.6 0 0.18 0.05], 'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor, ...
    'String', 'Plot Settings','Callback',@(src,event) pspec_settings_callback(h));

h.specgram_tab = uitab(h.SpectralTabs, 'Title', 'Spectrogram',    'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
h.specgram_plot_button = uicontrol('Style', 'pushbutton','Parent', h.specgram_tab,'String', 'Plot Spectrogram', ...
'Units', 'normalized','Position', [0.80, 0.0, 0.18, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) plot_specgram(h));
h.specgram_plot_setting_button = uicontrol('Style', 'pushbutton','Parent', h.specgram_tab,'String', 'Plot Settings', ...
'Units', 'normalized','Position', [0.60, 0.0, 0.18, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
'Callback', @(src, event) specgram_settings(h));


% Time Controls
h.startLabel_specgram = uicontrol('Parent', h.specgram_tab, ...
    'Style','text','Units','normalized','Position', [0.0 0.01 0.2 0.03], ...
    'String','Start Time, End Time','BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);

h.timeBox_specgram = uicontrol('Parent', h.specgram_tab, ...
    'Style','edit','Units','normalized','Position',[0.22 0.01 0.2 0.04], ...
    'String','0,1','Callback', @(src,evt) plot_specgram(h,src));
end
guidata(h.figure,h);
end
function updateSTDValue(src, handles,stdval)
    h = guidata(handles.figure);
    % Callback function to update STD value
    new_val = get(src, 'Value');
    set(stdval, 'String', num2str(new_val, '%.1f'));
    update_thresholds(h);
    
end