function create_signal_tabs(h)
backgdcolor = [1, 1, 1]; % Background Colours RGB - default white
accentcolor = [0.1, 0.4, 0.6]; % Accent Colours RGB
% if ~isfield(h,'overviewTabs') || ~isvalid(h.waterfall_tab)
%     %% Nested Tabs - Signal Overview
%     h.overview_main_tab   = uitab(h.tabgroup1, 'Title', 'Signal Traces','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
%     h.overviewTabs = uitabgroup('Parent', h.overview_main_tab,'Units', 'normalized','Position', [0 0 1 1]);
%     % Waterfall Plots
%     h.waterfall_tab = uitab(h.overviewTabs, 'Title', 'Waterfall Plots', 'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
%     h.waterfall_plot_button = uicontrol('Style', 'pushbutton','Parent', h.waterfall_tab,'String', 'Plot', ...
%     'Units', 'normalized','Position', [0.80, 0.0, 0.18, 0.05], ... 
%     'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
%     'Callback', @(src, event) pop_graph_callback(h));
%     %Controls for Waterfall Tab
%     h.startLabel_waterfall = uicontrol('Parent', h.waterfall_tab, ...
%         'Style', 'text','Units', 'normalized','Position', [0.0 0.01 0.2 0.03], ...
%         'String', 'Start Time, End Time','BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);
%     h.timeBox_waterfall = uicontrol('Parent', h.waterfall_tab, ...
%         'Style','edit','Units','normalized','Position',[0.22 0.005 0.2 0.04], ...
%         'String','0,1','Callback', @(src,evt) pop_graph_callback(h,src));
%     h.excluded_chansLabel_waterfall = uicontrol('Parent', h.waterfall_tab, ...
%         'Style', 'text','Units','normalized','Position', [0.42 0.01 0.2 0.03], ...
%         'String', 'Excluded Channels','BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);
%     h.excluded_chans_waterfall = uicontrol('Parent', h.waterfall_tab, ...
%         'Style','edit','Units','normalized','Position',[0.62 0.005 0.1 0.04], ...
%         'String','', 'Callback', @(src,evt) pop_graph_callback(h,[],src));
% 
%     % Channel Traces
%     h.traces_tab    = uitab(h.overviewTabs, 'Title', 'Signal Traces',   'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
%     h.traces_tab_button = uicontrol('Style', 'pushbutton','Parent', h.traces_tab,'String', 'Plot', ...
%     'Units', 'normalized','Position', [0.80, 0.0, 0.18, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, 'Callback', @(src, event) update_traces_tabs(h));
%     % Add std_textbox within the tab2 panel (h.tab2)
%     h.std_textbox = uicontrol( ...
%         'Parent', h.figure, ...
%         'Style', 'text', ...
%         'Units', 'normalized', ...
%         'Position', [0.23 0.05 0.05 0.04], ...
%         'HorizontalAlignment', 'Left', ...
%         'FontName', 'Calibri', ...
%         'BackgroundColor', get(h.traces_tab, 'BackgroundColor'), ...
%         'Fontsize', 9, ...
%         'ForegroundColor',accentcolor,'String', 'Spike Thresh (min.xSTDEV)');
%     h.std_value = uicontrol(...
%         'Parent', h.figure, ...
%         'Style', 'text', ...
%         'Units', 'normalized', ...
%         'Position', [0.28 0.035 0.02 0.04], ...
%         'FontName', 'Calibri', ...
%         'BackgroundColor', get(h.traces_tab, 'BackgroundColor'), ...
%         'Fontsize', 9, ...
%         'ForegroundColor',accentcolor,'String', '4.5'); % Default value
%     h.std_slider = uicontrol(...
%         'Parent', h.figure, ...
%         'Style', 'slider', ...
%         'Units', 'normalized', ...
%         'Position', [0.32 0.06 0.1 0.02], ...
%         'Min', 1, ...
%         'Max', 10, ...
%         'Value', 4.5, ...
%         'SliderStep', [0.5/9 2/9], ...
%         'BackgroundColor', get(h.traces_tab, 'BackgroundColor'), ...
%         'Callback', @(src, event) updateSTDValue(src, h,h.std_value));
% 
%     h.stdmax_textbox = uicontrol( ...
%         'Parent', h.figure, ...
%         'Style', 'text', ...
%         'Units', 'normalized', ...
%         'Position', [0.23 0.01 0.05 0.04], ... 
%         'HorizontalAlignment', 'Left', ...
%         'FontName', 'Calibri', ...
%         'BackgroundColor', get(h.traces_tab, 'BackgroundColor'), ...
%         'ForegroundColor',accentcolor,'Fontsize', 9, ...
%         'String', 'Spike Thresh (max.xSTDEV)');
%     h.stdmax_value = uicontrol(...
%         'Parent', h.figure, ...
%         'Style', 'text', ...
%         'Units', 'normalized', ...
%         'Position', [0.28 0.01 0.02 0.04], ...
%         'FontName', 'Calibri', ...
%         'BackgroundColor', get(h.traces_tab, 'BackgroundColor'), ...
%         'ForegroundColor',accentcolor,'Fontsize', 9, ...
%         'String', '7'); % Default value
%     h.stdmax_slider = uicontrol(...
%         'Parent', h.figure, ...
%         'Style', 'slider', ...
%         'Units', 'normalized', ...
%         'Position', [0.32 0.03 0.1 0.02], ...
%         'Min', 1, ...
%         'Max', 100, ...
%         'Value', 7, ...
%         'SliderStep', [1/99 10/99], ...
%         'BackgroundColor', get(h.traces_tab, 'BackgroundColor'), ...
%         'Callback', @(src, event) updateSTDValue(src, h,h.stdmax_value));
% 
%     % Format Toggle Group: Raw, Filtered, Referenced Signal Toggle
%     h.formatToggleGroup = uibuttongroup('Parent', h.probe_map_tab, ...
%         'Units', 'normalized', ...
%         'Position', [0.35, 0.0, 0.65, 0.05], ...  % top right within tab group
%         'BackgroundColor', backgdcolor, ...
%         'ForegroundColor', accentcolor, ...
%         'SelectionChangedFcn', @portSelectionChanged);
% end
% if  ~isfield(h,'QCTabs') || ~isvalid(h.QCTabs)
%     if ~isfield(h,'quality_metrics_tab') || ~isvalid(h.quality_metrics_tab)
%         h.quality_metrics_tab = uitab(h.tabgroup2, 'Title', 'Quality Check','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
%         h.QCTabs = uitabgroup('Parent', h.quality_metrics_tab,'Units', 'normalized','Position', [0 0 1 1]);
%     end
%     h.noise_tab  = uitab(h.QCTabs, 'Title', 'Noise Levels','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
%     h.noise_button = uicontrol('Style', 'pushbutton','Parent', h.noise_tab,'String', 'Plot Noise Levels', ...
%     'Units', 'normalized','Position', [0.80, 0.0, 0.20, 0.05], ... 
%     'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
%     'Callback', @(src, event) noise_plot_callback(h));    
% end
% if ~isfield(h,'freq_analysis_tab') || ~isvalid(h.freq_analysis_tab)
%     h.freq_analysis_tab   = uitab(h.tabgroup1, 'Title', 'Frequency Analysis','BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
%     %% Nested Tabs - Frequency Analysis
%     h.SpectralTabs = uitabgroup('Parent', h.freq_analysis_tab, 'Units', 'normalized', 'Position', [0 0 1 1]);
%     h.pspec_tab    = uitab(h.SpectralTabs, 'Title', 'Power Spectrum',  'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
%     h.ps_plot_button = uicontrol('Style', 'pushbutton','Parent', h.pspec_tab,'String', 'Plot', ...
%     'Units', 'normalized','Position', [0.80, 0.0, 0.18, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
%     'Callback', @(src, event) update_power_spectrum_tab(h));
%     h.pspec_toggle = uicontrol('Style', 'checkbox','Parent', h.pspec_tab,'Units', 'normalized', ...
%         'Position', [0.05 0 0.2 0.04], 'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor, ...
%         'FontName', 'Cambria', 'FontSize', 11, 'String', 'Global', 'Value', 0,'Callback',@(src,event) update_power_spectrum_tab(h)); 
% 
%     h.specgram_tab = uitab(h.SpectralTabs, 'Title', 'Spectrogram',    'BackgroundColor', backgdcolor, 'ForegroundColor', accentcolor);
%     h.specgram_plot_button = uicontrol('Style', 'pushbutton','Parent', h.specgram_tab,'String', 'Plot Spectrogram', ...
%     'Units', 'normalized','Position', [0.80, 0.0, 0.18, 0.05], 'BackgroundColor',backgdcolor,'ForegroundColor',accentcolor, ...
%     'Callback', @(src, event) plot_specgram(h));
%     h.specgram_plots_axes = axes('Parent', h.specgram_tab, ...
%         'Units', 'normalized',...
%         'Position', [0.1 0.1 0.85 0.85],...
%         'FontName', 'Cambria',...
%         'Fontsize', 8,'Visible','off');
% 
%     % Time Controls
%     h.startLabel_specgram = uicontrol('Parent', h.specgram_tab, ...
%         'Style','text','Units','normalized','Position', [0.0 0.01 0.2 0.03], ...
%         'String','Start Time, End Time','BackgroundColor', backgdcolor,'ForegroundColor', accentcolor);
% 
%     h.timeBox_specgram = uicontrol('Parent', h.specgram_tab, ...
%         'Style','edit','Units','normalized','Position',[0.22 0.01 0.2 0.04], ...
%         'String','0,1','Callback', @(src,evt) plot_specgram(h,src));
% end
    % guidata(h.figure,h);
init_traces_tab(h);
update_traces_tab(h);
init_power_spectrum_tab(h);
end
function updateSTDValue(src, handles,stdval)
    h = guidata(handles.figure);
    % Callback function to update STD value
    new_val = get(src, 'Value');
    set(stdval, 'String', num2str(new_val, '%.1f'));
    update_thresholds(h);
    
end