function plot_network_graph(h, adjacency_matrix, x_coords, y_coords, unique_channels, ...
    receiver_nodes, sender_nodes, broker_nodes, node_degrees)
    set_status(h.figure,"loading","Plotting Network Connectivity Graph...");

    G = graph(adjacency_matrix, 'upper','omitselfloops');

    % Clear old axes
    delete(findobj(allchild(h.nc_tab), 'Type','axes'));

    h.network_connectivity_map = subplot(1,2,1,'Parent',h.nc_tab);
    p = plot(G, ...
        'XData', x_coords(unique_channels+1), ...
        'YData', y_coords(unique_channels+1), ...
        'LineWidth', G.Edges.Weight*2, ...
        'EdgeColor', [0.5 0.5 0.5], ...
        'NodeColor', 'none', ...
        'NodeLabel', unique_channels);

    % Edge coloring
    p.EdgeCData = G.Edges.Weight;
    colormap('turbo');
    colorbar('southoutside'); caxis([0 1]);
    hold all

    % Node classification colors
    receiver_color = [128/255, 0, 32/255]; %red
    sender_color = [0 0 139/255]; % blue
    broker_color = [250/255 140/255 0]; % green

    % Marker sizes from degree
    marker_sizes(node_degrees <= 5) = 50; 
    marker_sizes(node_degrees > 5 & node_degrees <= 10) = 100; 
    marker_sizes(node_degrees > 10 & node_degrees <= 15) = 150; 
    marker_sizes(node_degrees > 15) = 200;
    % Plotting receiver nodes
    hReceiver = scatter( ...
        x_coords(unique_channels(receiver_nodes) + 1), ...
        y_coords(unique_channels(receiver_nodes) + 1), ...
        marker_sizes(receiver_nodes), ...
        'o', ...
        'MarkerFaceColor', receiver_color, ...
        'MarkerEdgeColor', receiver_color);
    
    % Plotting sender nodes
    hSender = scatter( ...
        x_coords(unique_channels(sender_nodes) + 1), ...
        y_coords(unique_channels(sender_nodes) + 1), ...
        marker_sizes(sender_nodes), ...
        'o', ...
        'MarkerFaceColor', sender_color, ...
        'MarkerEdgeColor', sender_color);
    
    % Plotting broker nodes
    hBroker = scatter( ...
        x_coords(unique_channels(broker_nodes) + 1), ...
        y_coords(unique_channels(broker_nodes) + 1), ...
        marker_sizes(broker_nodes), ...
        'o', ...
        'MarkerFaceColor', broker_color, ...
        'MarkerEdgeColor', broker_color);
    
    ax = h.network_connectivity_map;
    axis(ax,'square');
    ax.YDir = 'reverse';
    set(ax,'Color','none');  
    lg = legend([hReceiver, hSender, hBroker], ...
                {'Receiver Nodes','Sender Nodes','Broker Nodes'}, ...
                'Location','northoutside','Orientation','horizontal');
    lg.Position = [0.35 0.01 0.1 0.05];  

    title('Network Graph Based on STTC');
    axtoolbar({'save','zoomin','zoomout','restoreview','pan'});box off;
    set_status(h.figure,"loading","Plotting Network Connectivity Graph...");

end
